### ISSUE TITLE
Add documentation about the command line support

### ISSUE THREAD

**Issue by jk-1** [MaranBr/Systemback#1]
Please add documentation of the possible command line API

Is it possible to run Systemback features from command line?
System backup
System copy
System install
System repair
System restore
System upgrade
Live system create

What is the output of  `systemback --help` ?

I am looking for a command line tool which can create/update a bootable .iso from my Ubuntu 20/22 system as a part of a system maintenance script.

**Comment by MaranBr** [comment]
Systemback command line interface is very limited. It only allows you to create restore points. You can’t create a live ISO file.
